### ISSUE TITLE
Sketch components boundaries

### ISSUE THREAD

**Issue by UXLana** [endswithak/sketch-measure-react#1]
Hi! 
Thanks so much for this plugin - much-needed feature for Sketch. One thing though that's stopping me from introducing it to the team is (unless I'm missing something), that it doesn't respect the boundaries of nested symbols. It selects the deepest layer, which is often smaller than the actual component's bounding box, which is likely to include padding.
With that update included, I feel it would be ideal plugin for our dev handoff process.
Kind regards,
Lana

**Comment by madebyerik** [comment]
Thanks for the feedback! Currently, all layers are ungrouped before render. The only way to introduce a bounding-box is to add an extra layer to your symbol or group with your preferred bounding dimensions. E.g. if your symbol is 100x100, and you want a 100x100 bounding box, you would add a 100x100 rectangle as the last layer in the symbol.

**Comment by madebyerik** [comment]
The next release will support groups along with a bunch of other cool features. It will be out in a day or two.

**Comment by UXLana** [comment]
Thanks so much for your response! I will try adding the bounding box and
will be looking forward to the next release!

Kind regards,
Lana Sidorovskaya

**Comment by madebyerik** [comment]
Groups are now supported.
