### ISSUE TITLE
Invalid Selection error

### ISSUE THREAD

**Issue by aaronspransy** [endswithak/sketch-measure-react#2]
I can't seem to get plugin to work. I keep getting an "Invalid Selection" Select and artboard to export message. Even though I have an artboard already selected. I tried several different Sketch files but still won't work. Any suggestions?

**Comment by madebyerik** [comment]
What version of sketch are you running?

**Comment by aaronspransy** [comment]
Version 62

**Comment by madebyerik** [comment]
You're selecting an artboard, correct? Not just a group of layers?
